name: freelancekisan_user
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  splashscreen: ^1.3.5
  firebase: ^9.0.0
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.0
  fluttertoast: ^7.1.6
  cupertino_icons: ^1.0.0
  google_maps_flutter: ^2.0.1
  geocoder: ^0.2.1
  provider: ^5.0.0
  http: ^0.13.0
  geolocator: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - Images/
